## Implementation of SVD
*   Author: Sanjay S Rao
*   LinkedIn: https://www.linkedin.com/in/sanjay-srinivasa-rao-b67a771a0/
*   e-mail - sanjay.s.rao04@gmail.com

In [1]:
import numpy as np
from scipy.linalg import svd,eig
import math

### Using in-built function

In [2]:
A = np.array([[4,0],[3,-5]])
U, S, VT = svd(A)

In [3]:
print("Left singular vectors: ")
print(U)
print("Singular Values: ")
print(np.diag(S))
print("Right singular vectors: ")
print(VT)

Left singular vectors: 
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
Singular Values: 
[[6.32455532 0.        ]
 [0.         3.16227766]]
Right singular vectors: 
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [4]:
sigma = np.diag(S)

In [5]:
print(U @ sigma @ VT)

[[ 4.00000000e+00 -1.11022302e-15]
 [ 3.00000000e+00 -5.00000000e+00]]


In [6]:
T = np.dot(U,sigma)
T

array([[-2.82842712, -2.82842712],
       [-5.65685425,  1.41421356]])

In [7]:
np.dot(T,VT)

array([[ 4.00000000e+00, -1.11022302e-15],
       [ 3.00000000e+00, -5.00000000e+00]])

The number of features to be extracted (n_components) are decided while creating a sigma matrix. For instance, if our original matrix is of size 1000x100 and if we want to experiment by choosing only top 10 features, then our sigma matrix should be framed only with 10 diagonal values.

**Note:** Choice of diagonal values is never random, bcz the rule for framing a sigma matrix is "The singular values are to be arranged in descending order diagonally."

As we know that the sigma matrix is the diagonal matrix of singular values, thus the reduced features are obtained by transformation invovling the sigma matrix. In order to transform, we follow a two-step procedure.
- Step-1: Multiply sigma with U i.e., T1 = U.sigma  (dot product)
- Step-2: Multiply T1 with V i.e., T2 = T1.V  where V - E.vector matrix

Since the extraction involves the singular values as the major criteria, thus the name **Singular Value Decomposition**

### Without in-built function

In [8]:
A = np.array([[4,0],[3,-5]])
ATA = np.dot(np.transpose(A),(A))
ATA

array([[ 25, -15],
       [-15,  25]])

In [9]:
cov_matrix = np.cov(ATA.T)
cov_matrix

array([[ 800., -800.],
       [-800.,  800.]])

In [10]:
evalues, evectors = np.linalg.eig(ATA)

In [11]:
evalues

array([40., 10.])

In [12]:
evectors

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [13]:
S = np.sqrt(evalues)
sigma = np.diag(S)
sigma

array([[6.32455532, 0.        ],
       [0.        , 3.16227766]])

In [14]:
V = evectors
VT = np.transpose(V)

In [15]:
sigma_inv = np.linalg.inv(sigma)

In [16]:
U = A @ V @ sigma_inv
U

array([[ 0.4472136 ,  0.89442719],
       [ 0.89442719, -0.4472136 ]])

In [17]:
SVD_A = U @ sigma @ VT
SVD_A

array([[ 4.,  0.],
       [ 3., -5.]])

In [18]:
T1 = np.dot(U,sigma)
T1

array([[ 2.82842712,  2.82842712],
       [ 5.65685425, -1.41421356]])

In [19]:
T2 = np.dot(T1,V)
T2

array([[4.4408921e-16, 4.0000000e+00],
       [5.0000000e+00, 3.0000000e+00]])

## **TASK:**

1. Create a singular matrix for 3x3 array & perform all the transformation tasks that are required to extract top 2 features.
2. Using a real-world dataset perform feature extraction using SVD. Justify your result by comparing with PCA and LDA

In [20]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([[-1,2,0],[2,0,-2],[0,-2,1]])

#A = array(x)
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s) #if any error chnge shape to 1
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)
#print(U)

[[-1  2  0]
 [ 2  0 -2]
 [ 0 -2  1]]
[[-1.00000000e+00  2.00000000e+00 -3.33066907e-16]
 [ 2.00000000e+00  1.11022302e-16 -2.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  1.00000000e+00]]
[[-1.78885438 -1.34164079]
 [-0.89442719  2.68328157]
 [ 2.23606798  0.        ]]
[[-1.78885438e+00 -1.34164079e+00]
 [-8.94427191e-01  2.68328157e+00]
 [ 2.23606798e+00  2.22044605e-16]]


## nrows < ncolumns case

In [21]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define a matrix
#A = array([[1,2,3],[11,12,13],[21,22,23]])
A = array([[-1,2,0,4],[2,0,-2,1],[0,-2,1,3]])

#A = array(x)
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s) #if any error chnge shape to 1
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)
#print(U)

[[-1  2  0  4]
 [ 2  0 -2  1]
 [ 0 -2  1  3]]
[[-0.14843327  1.14843327 -0.42578337  4.21880078]
 [ 0.59373307  1.40626693 -1.29686654  0.63867505]
 [-0.98048356 -1.01951644  1.49024178  2.74807544]]
[[ 4.28024566 -1.        ]
 [ 0.64797706 -2.        ]
 [ 2.78809989  2.        ]]
[[ 4.28024566 -1.        ]
 [ 0.64797706 -2.        ]
 [ 2.78809989  2.        ]]
